### ISSUE TITLE
Todoist project comment link should be more than one letter

### ISSUE THREAD

**Issue by geoelectric** [dennisseidel/obsidian-todoist-link#2]
It’s pretty cryptic to come back to later, and it’s considerably more difficult to tap on a single “o” on a small mobile screen than on a word. The comment is editable, but annoying to do that every time.

It’s a little surprising this isn’t “[Obsidian]” given the other link is “[Todoist]”. Ideally it’d be configurable.

**Comment by geoelectric** [comment]
Turns out this is even worse on Todoist Desktop, because on there (and website) it doesn't give you the opportunity to edit the link text--unless you can put your cursor between two characters. Only Mobile expands it to Markdown so you can edit in place, and the "Add/Edit Link" dialog otherwise only lets you change the destination.

So, currently, you have to copy the link destination, delete the link entirely, and recreate it as "Obsidian". For a better desktop/web workflow it's going to be important this is multiple characters.

**Comment by tim-hilde** [comment]
@dennisseidel  I have created a PR for this issue. It'd be great to integrate this.

**Comment by dennisseidel** [comment]
@tim-hilde  @geoelectric Thank you very much 🙏 - somehow my github email notifications where off. I included your PR in the current version 2.1.0.
