### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by tb-1212** [dennisseidel/obsidian-todoist-link#5]
hi! I cannot seem to be able to create a task in Todoist

**Comment by github-187** [comment]
Hi, me neither. I reinstalled the plugin but it didn't work.

**Comment by b4good** [comment]
Same for me. Just doesn't do anything... :(

**Comment by igorterroso** [comment]
There seems to be a CORS policy issue currently and todoist is blocking the requests coming from Obsidian Todoist Link...

Access to XMLHttpRequest at 'https://api.todoist.com/rest/v1/tasks' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by guihasparyk** [comment]
> There seems to be a CORS policy issue currently and todoist is blocking the requests coming from Obsidian Todoist Link...
> 
> Access to XMLHttpRequest at 'https://api.todoist.com/rest/v1/tasks' from origin 'app://obsidian.md' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Knowing the source of the issue, what would be the order of magnitude of it? Is it fixable, and how much time would take to fix it?  🤔

**Comment by vitaly74** [comment]
wow;( maybe somebody know how to fix it? this plugin was one of top5 for me:(

**Comment by dennisseidel** [comment]
Thanks for reaching out. I fix the issue in the new plugin version 2.0.6. 

Todoist upgraded their API to v2 and deprecated the old v1 api. This led to the issue.
